import { assets } from "../../assets/data";

export const dummyProperties = [
  // Indore Properties
  {
    id: 1,
    image: assets.bgImage,
    name: "Modern Family Home",
    description: "Luxurious and cozy home with modern amenities.",
    city: "Indore",
    country: "India",
    type: "Villa",
    address: "123 Main Street",
    area: 2800,
    price: "$350,000",
    salePrice: "$340,000",
    rentPrice: "$1,500/mo",
    bedrooms: 4,
    bathrooms: 3,
    garages: 2,
    amenities: ["parking", "wifi", "backyard", "terrace"],
  },
  {
    id: 2,
    image: assets.heroHomeImage,
    name: "Elegant Townhouse",
    description: "Spacious townhouse in a quiet Indore neighborhood.",
    city: "Indore",
    country: "India",
    type: "Townhouse",
    address: "45 Riverside Drive",
    area: 2000,
    price: "$250,000",
    salePrice: "$240,000",
    rentPrice: "$1,200/mo",
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    amenities: ["wifi", "terrace"],
  },
  {
    id: 3,
    image: assets.HeroBackImage,
    name: "Luxury Penthouse",
    description: "Premium penthouse with city skyline view.",
    city: "Indore",
    country: "India",
    type: "Penthouse",
    address: "78 Central Plaza",
    area: 3500,
    price: "$500,000",
    salePrice: "$480,000",
    rentPrice: "$2,500/mo",
    bedrooms: 5,
    bathrooms: 4,
    garages: 3,
    amenities: ["parking", "wifi", "terrace", "backyard"],
  },

  // Bhopal Properties
  {
    id: 4,
    image: assets.heroHomeImage,
    name: "Luxury Apartment",
    description: "Elegant apartment in city center with premium facilities.",
    city: "Bhopal",
    country: "India",
    type: "Apartment",
    address: "45 Central Avenue",
    area: 1800,
    price: "$220,000",
    salePrice: "$210,000",
    rentPrice: "$900/mo",
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    amenities: ["wifi", "terrace"],
  },

  // Indore Properties
  {
    id: 5,
    image: assets.HeroBackImage,
    name: "Cozy Cottage",
    description: "Perfect countryside retreat with backyard and terrace.",
    city: "Indore",
    country: "India",
    type: "Cottage",
    address: "22 Hill Street",
    area: 1500,
    price: "$180,000",
    salePrice: "$170,000",
    rentPrice: "$800/mo",
    bedrooms: 2,
    bathrooms: 2,
    garages: 1,
    amenities: ["parking", "backyard"],
  },
  {
    id: 6,
    image: assets.bgImage,
    name: "Sea View Villa",
    description: "Beautiful villa with sea view and modern amenities.",
    city: "Mumbai",
    country: "India",
    type: "Villa",
    address: "88 Ocean Drive",
    area: 3000,
    price: "$450,000",
    salePrice: "$440,000",
    rentPrice: "$2,000/mo",
    bedrooms: 4,
    bathrooms: 3,
    garages: 2,
    amenities: ["parking", "wifi", "terrace", "backyard"],
  },
];
